"""initial

Revision ID: 2c17e0261670
Revises: 
Create Date: 2026-07-19 02:21:52.864129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c17e0261670'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('maneuvers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'FINALIZADA', name='maneuver_status'), nullable=False),
    sa.Column('header_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('topology_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.UUID(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('maneuver_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maneuver_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.Enum('ABRIR', 'FECHAR', name='maneuver_action'), nullable=True),
    sa.Column('origin', sa.Enum('SIMULADOR', 'MANUAL', name='maneuver_step_origin'), nullable=False),
    sa.ForeignKeyConstraint(['maneuver_id'], ['maneuvers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maneuver_substations',
    sa.Column('maneuver_id', sa.UUID(), nullable=False),
    sa.Column('substation_id', sa.UUID(), nullable=False),
    sa.Column('substation_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maneuver_id'], ['maneuvers.id'], ),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('maneuver_id', 'substation_id')
    )
    op.create_table('provisional_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('maneuver_id', sa.UUID(), nullable=False),
    sa.Column('substation_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('JUMPER', 'CHAVE_PROVISORIA', name='provisional_element_type'), nullable=False),
    sa.Column('properties_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['maneuver_id'], ['maneuvers.id'], ),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('substation_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('substation_id', sa.UUID(), nullable=False),
    sa.Column('topology_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('saved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['saved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['substation_id'], ['substations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('substation_versions')
    op.drop_table('provisional_elements')
    op.drop_table('maneuver_substations')
    op.drop_table('maneuver_steps')
    op.drop_table('substations')
    op.drop_table('maneuvers')
    op.drop_table('users')
    # ### end Alembic commands ###
