"""remove origin de maneuver_steps

Revision ID: 9fef7d796fa0
Revises: aad168c3900f
Create Date: 2026-07-27 12:44:36.873172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fef7d796fa0'
down_revision: Union[str, None] = 'aad168c3900f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maneuver_steps', 'origin')
    # ### end Alembic commands ###
    # drop_column não derruba o tipo ENUM sozinho (fica órfão) — sem isso, rodar
    # upgrade de novo depois de um downgrade falha com "type already exists"
    # (mesmo cuidado da migration aad168c3900f).
    sa.Enum(name='maneuver_step_origin').drop(op.get_bind(), checkfirst=True)


def downgrade() -> None:
    # op.add_column não recria o tipo ENUM sozinho fora de op.create_table —
    # precisa criar explicitamente antes (mesmo padrão de aad168c3900f).
    postgresql.ENUM('SIMULADOR', 'MANUAL', name='maneuver_step_origin').create(op.get_bind(), checkfirst=True)
    # server_default é necessário pra popular as linhas já existentes — sem
    # isso o ADD COLUMN NOT NULL falha com "contains null values" numa tabela
    # não vazia (mesmo motivo do server_default em `responsibility`, aad168c3900f).
    op.add_column(
        'maneuver_steps',
        sa.Column(
            'origin',
            postgresql.ENUM('SIMULADOR', 'MANUAL', name='maneuver_step_origin'),
            server_default='MANUAL',
            nullable=False,
        ),
    )
