"""adiciona number em maneuvers e responsibility em maneuver_steps

Revision ID: aad168c3900f
Revises: 2c17e0261670
Create Date: 2026-07-27 11:06:00.191130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'aad168c3900f'
down_revision: Union[str, None] = '2c17e0261670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column não cria o tipo ENUM sozinho fora de op.create_table
    # (diferente de create_all/metadata) — precisa criar explicitamente antes.
    postgresql.ENUM('LOCAL', 'CENTRO', name='maneuver_step_responsibility').create(op.get_bind(), checkfirst=True)
    op.add_column('maneuver_steps', sa.Column('responsibility', sa.Enum('LOCAL', 'CENTRO', name='maneuver_step_responsibility'), server_default='CENTRO', nullable=False))
    op.add_column('maneuvers', sa.Column('number', sa.String(length=20), nullable=True))
    op.create_unique_constraint('uq_maneuvers_number', 'maneuvers', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_maneuvers_number', 'maneuvers', type_='unique')
    op.drop_column('maneuvers', 'number')
    op.drop_column('maneuver_steps', 'responsibility')
    # ### end Alembic commands ###
    # drop_column não derruba o tipo ENUM sozinho (fica órfão) — sem isso, rodar
    # upgrade de novo depois de um downgrade falha com "type already exists".
    sa.Enum(name='maneuver_step_responsibility').drop(op.get_bind(), checkfirst=True)
